name: Crypto Finance Education

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate Crypto Post
      env:
        POE_API_KEY: ${{ secrets.POE_API_KEY }}
      run: python generate_post.py "Understanding Bitcoin Halving"

    - name: Generate Finance Post
      env:
        POE_API_KEY: ${{ secrets.POE_API_KEY }}
      run: python generate_post.py "Personal Finance Basics: Budgeting and Saving"

    - name: Generate Making Money Post
      env:
        POE_API_KEY: ${{ secrets.POE_API_KEY }}
      run: python generate_post.py "Side Hustles You Can Start Today"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '_posts'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/crypto-finance-education
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
